#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

#
# This is a copy of the docker-compose-cli.yml that is available in the DSpace/DSpace
# (Backend) at:
# https://github.com/DSpace/DSpace/blob/main/docker-compose-cli.yml
#
# Therefore, it should be kept in sync with that file
version: "3.7"

services:
  dspace-cli:
    image: "${DOCKER_OWNER:-dspace}/dspace-cli:${DSPACE_VER:-dspace-7_x}"
    container_name: dspace-cli
    #environment:
    volumes:
    - "assetstore:/dspace/assetstore"
    - "./local.cfg:/dspace/config/local.cfg"
    entrypoint: /dspace/bin/dspace
    command: help
    networks:
      - dspacenet
    tty: true
    stdin_open: true

volumes:
  assetstore:

networks:
  dspacenet:
